### ISSUE TITLE
Login veto error information and translation

### ISSUE THREAD

**Issue by Kaik** [zikula-modules/Legal#19]
Hi,
When logging in and policies need to be accepted an error message occurs.
https://github.com/zikula-modules/Legal/blob/master/Listener/UsersLoginVeto.php#L97
I have tried to translate it but looks like translation is not working (is this domain issue?)

Please consider to remove this error message or change it to information message as there is already similar message in templates and altogether it looks confusing.

**Comment by Guite** [comment]
The module is now using the translator service. In case you still experience translation problems please create a new issue. I am going to test it for #51 though.
