### ISSUE TITLE
Interactive upgrade

### ISSUE THREAD

**Issue by hvorragend** [zikula-modules/Legal#2]
I've noticed that after upgrading the Core the user must suddenly accept the conditions.
Unfortunately the administrator has no way to control this practice. And some users might be surprised.

As we have already discussed, it would be an advantage if we ask the admin in an interactive module upgrade how to proceed.

**Comment by Guite** [comment]
First this behaviour is not related to core upgrades. I suspect that after this functionality (check for missing site policy confirmation during login) has been introduced in the Legal module you received this Legal version together with a core upgrade.
The Legal settings page allows to reset confirmation state for certain user groups. So the administrator is indeed able to control when new confirmations are required from specific users.

Closing.
