### ISSUE TITLE
The Module Var "legalNoticeActive" Doesn't Do Anything When Set

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Legal#34]
When you set the module var "legalNoticeActive" to true here:

index.php?module=legalmod&type=admin&func=modifyConfig

It doesn't do anything in the User Registration form. Even when you set a value for "legalNoticeUrl", it still does not display anything.

**Comment by Guite** [comment]
This is expected behaviour. Legal notice and accessibility statement do not need to be confirmed by the user.
