### ISSUE TITLE
Adding Support for Webshim and Polyfill

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Legal#50]
The Zikula core supports Webshim, which is a polyfill library that enables you to reliably use HTML5 features across browsers, even if native support is lacking.

The module Legal should be updated to take advantage of its features.

Also, the module Legal can potentially add additional custom validations, by just attaching to the "blur" event on fields.

Refs. https://github.com/zikula/core/pull/2377

**Comment by Guite** [comment]
This has been done as part of #55
