### ISSUE TITLE
the legal version shipped with 1.4.2 gives error during installation

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Legal#53]
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Zikula\LegalModule\LegalModuleInstaller must implement ExtensionInstallerInterface

**Comment by craigh** [comment]
closed in favor of https://github.com/zikula/core/issues/2831
