### ISSUE TITLE
Policy acceptance after initial login is not saved

### ISSUE THREAD

**Issue by Guite** [zikula-modules/Legal#63]
When a new user has been created by an admin he needs to accept site policies during his initial login. This setting is not correctly saved though.

@craigh This is a blocker for the 1.4.4 release.

**Comment by craigh** [comment]
![screen shot 2016-11-25 at 10 53 16 am](https://cloud.githubusercontent.com/assets/350048/20630177/6d13e330-b2fd-11e6-8498-a7fd1448faa7.png)

this seems to be a good sign.
