### ISSUE TITLE
not all translations are used

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Legal#66]
Zikula 1.4.6 ci 107
legal 3.0.0

![grafik](https://cloud.githubusercontent.com/assets/935250/22618947/0eb76b20-eaea-11e6-905a-53bfa1efd535.png)
As you may see there are several strings not translated. But they are translated in the po files propperly
[translations.zip](https://github.com/zikula-modules/Legal/files/752309/translations.zip)

**Comment by craigh** [comment]
all the non-translated strings are in the Form class I think.

**Comment by craigh** [comment]
meaning this is probably a core bug. But leave here for now.

**Comment by craigh** [comment]
hmm - I guess Legal isn't using Form yet?

**Comment by Guite** [comment]
Only for the config page, not for the hooks stuff, since the fields are embedded into the register form.

**Comment by craigh** [comment]
this was caused by using an old translation file.  the `Resources/translations/zikula.en.po` is now removed and should not be used. All translations for the LegalModule go in `Resources/translations/zikulalegalmodule.*.po`

**Comment by craigh** [comment]
![screen shot 2017-05-13 at 8 44 27 am](https://cloud.githubusercontent.com/assets/350048/26025568/f2888b16-37b8-11e7-9967-b1c54fc2978c.png)
